### ISSUE TITLE
WriteConsoleOutputCharacter in Windows terminal works well.

### ISSUE THREAD

**Issue by zmcj1** [Agrael1/Veritas-2D#5]
I have read your question on StackOverFlow : https://stackoverflow.com/questions/55560959/is-there-a-way-to-output-ansi-escape-sequences-using-low-level-output

According to my test results:

WriteConsoleOutputCharacterW does not work well with ANSI sequence in ConEmu and Console.
Because ConEmu and Console only parse the ANSI sequence sent by WriteConsole or WriteFile.

But the same API works well with ANSI sequence in Windows terminal !!!
So, it can reach the speed of WriteConsoleOutputW, but also support RGB 24-bit color.
I think this is perfect for your game.

**Comment by Agrael1** [comment]
Problem is for now that WriteConsoleOutputW is slow as well, so I had to move away from it for now: 86ms of time for one frame drop is not what a game (even in 16 colors) is good with.
